### PR TITLE
Add cross editor c++ linting config

### PR DESCRIPTION
**Pull request by mickvangelderen**
.clang_complete is understood by various editors. It provides information that linters and other tools can use.

### CODE REVIEW

**Comment by oliverlee** [comment]
What exactly does this do?

**Comment by oliverlee** [comment]
Thought you fixed this?

**Comment by mickvangelderen** [comment]
Though so too.

**Comment by mickvangelderen** [comment]
> What exactly does this do?

It lets me and potentially use clang as an in-editor linter.

**Pull request merged**
